server.port: 8082
pod.name: NOME_POD_TEST_SVIL  
spring.application.name: gfa-gestionale
gateway.host: "http://127.0.0.1:9090"

joinfaces:
  jsf:
    PROJECT_STAGE: Production
    FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: vela
tomcat:
  version: "@tomcat.version@"
jetty:
  version: "@jetty.version@"
undertow:
  version: "@undertow.version@"
application-users:
  users-credentials:
    - username: persapiens
      password: 123
      authorities: ROLE_ADMIN
    - username: nyilmaz
      password: qwe
      authorities: ROLE_USER
      
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: TRACE
#        cloud:
#          kubernetes: DEBUG